# Generated by Django 4.0.3 on 2022-05-27 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userpreferenceform_title_userpreferenceform_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreferenceform',
            old_name='user',
            new_name='userStuff',
        ),
    ]
