# Generated by Django 4.0.3 on 2022-05-27 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_rename_user_userpreferenceform_userstuff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferenceform',
            name='userStuff',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title', to=settings.AUTH_USER_MODEL),
        ),
    ]
