# Generated by Django 4.0.3 on 2022-05-29 23:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_userpreferenceform_userstuff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferenceform',
            name='title',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('politics', 'Politics'), ('covid-19', 'Covid-19'), ('trending', 'Trending'), ('international stories', 'International stories'), ('independent sources', 'Independent Sources'), ('sports', 'Sports'), ('war in ukraine', 'War in Ukraine')], max_length=90),
        ),
    ]
